src/MooseShield/Controllers/LoginController.cs
using log4net;
using RestSharp;
using EVE.SingleSignOn;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Configuration;
using EVE.SingleSignOn.Models;
using MooseShield.Models;
using MooseShield.Models.XmlCharacter;
using Newtonsoft.Json;

namespace MooseShield.Controllers
{
    public class LoginController : Controller
    {
        private ILog _log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Login
        public ActionResult Index()
        {

            return Redirect(SSOClient.GetAuthenticationUrl());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="code"></param>
        /// <param name="state"></param>
        /// <returns></returns>
        public async Task<ActionResult> CallBack(string code, string state)
        {
            
            _log.Debug($"Reached callback with the code {code}");
            SSOCharacter character = null;
            try
            {
                if (!SSOClient.IsLoggedIn)
                {
                    _log.Debug("User not logged in, authenticating");
                    AuthResponse authentication = await SSOClient.AuthenticateAsync(code);
                    if (authentication != null)
                    {
                        _log.Debug("Authentication complete, verifying");
                        character = await SSOClient.VerifyAsync(authentication.AccessToken);

                        if (character != null)
                        {
                            _log.Debug($"Verification complete with {character.CharacterName}");
                        }
                    }
                }
                else
                {
                    character = SSOClient.GetCharacter;
                    _log.Debug($"User already logged in with {character.CharacterName}");
                }
            }
            catch (Exception e)
            {
                _log.Error("Encountered issues while trying to authenticate user.", e);
            }

            try
            {
                if(character.CharacterName == "Keolae Moliko")
                {
                    return RedirectToAction("Create", "TeamSpeakUsers");
                }
                int saveResult = -1;
                if (character != null)
                {
                    // Get the user's public character info from the XML API
                    Result charInfo = await characterInfo(character.CharacterId);
                    // Check to see if the user is in the correct alliance
                    bool _CorrectAlliance = CorrectAlliance(charInfo);
                    // If the user isn't in the approved alliance deny access
                    if (!_CorrectAlliance)
                    {
                        _log.Info($"Redirecting {charInfo.CharacterName} to unauthorized page. Object: {JsonConvert.SerializeObject(charInfo)}");
                        Session.Clear();
                        Session.Abandon();
                        return RedirectToAction("NotMoose", "Unauthorised");
                    }

                    using (var context = new TSAuthContext("Local"))
                    {
                        User c = null;
                        try
                        {
                            c = context.Users.Where(u => u.CharacterID == character.CharacterId).Single();
                        }
                        catch (Exception e)
                        {
                            if (c == null)
                            {
                                
                                // save the new character to the DB
                                saveCharacter(character, context, charInfo);
                                saveResult = context.SaveChanges();                                                                   
                            }
                        }

                    }
                }
            }
            catch (Exception e)
            {
                _log.Error("Encountered a fault while doing TSAuth", e);
                throw;
            }

            return RedirectToAction("Create", "TeamSpeakUsers");
        }

        private async Task<Result> characterInfo(long characterId)
        {
            RestRequest request = new RestRequest();
            // Headers
            request.AddHeader("User-Agent", "Contact: helmy@threebeersaday.com");

            string url = "https://api.eveonline.com/eve/CharacterInfo.xml.aspx?characterID=" + characterId;
            RestClient client = new RestClient(url);
            IRestResponse<Result> response = await client.ExecuteTaskAsync<Result>(request);

            return response.Data;
        }

        private void saveCharacter(SSOCharacter character, TSAuthContext context, Result charInfo)
        {
            var c = new User()
            {
                CharacterID = character.CharacterId,
                CharacterName = character.CharacterName,
                CharacterOwnerHash = character.CharacterOwnerHash,
                Corporation = charInfo.Corporation,
                Alliance = charInfo.Alliance,
                CreatedAt = DateTime.Now
            };
            context.Users.Add(c);

        }

        public ActionResult logout()
        {
            // If the user is logged in, kill the session
            if (SSOClient.IsLoggedIn)
            {
                Session.Clear();
                Session.Abandon();
            }

            return RedirectToAction("Index", "Home");
        }


        /// <summary>
        /// Check to see if the requesing user is in an approved alliance
        /// </summary>
        /// <param name="charInfo"></param>
        /// <returns></returns>
        private bool CorrectAlliance(Result charInfo)
        {
            // Get the string of approved alliances from Web.config
            string alliance = ConfigurationManager.AppSettings["Alliance"];
            // Split the string and add values to an array
            string[] array = alliance.Split(',');
            // Check to see if the requesting user's alliance is approved
            bool allianceExists = Array.Exists(array, element => element == charInfo.Alliance);
            // If they aren't a member of Moose Federation kick them out
            if (!allianceExists)
            {
                return false;
            }
            // Continue with the signin process if the requesting user's alliance is approved
            return true;
        }
    }
}

// https://crest-tq.eveonline.com/alliances/99005677/ - Infamous

// https://crest-tq.eveonline.com/alliances/99005749/ - Inglorious

// https://crest-tq.eveonline.com/characters/95322597/

src/MooseShield/Controllers/ServerGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MooseShield.Action_Filters;
using MooseShield.Models;

namespace MooseShield.Controllers
{
    [RBAC]
    public class ServerGroupsController : Controller
    {
        private TSAuthContext db = new TSAuthContext();

        // GET: ServerGroups
        public ActionResult Index()
        {
            return View(db.ServerGroups.ToList());
        }

        // GET: ServerGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerGroup serverGroup = db.ServerGroups.Find(id);
            if (serverGroup == null)
            {
                return HttpNotFound();
            }
            return View(serverGroup);
        }

        // GET: ServerGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServerGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServerGroupID,ServerGroupName,TSServerGroupID")] ServerGroup serverGroup)
        {
            if (ModelState.IsValid)
            {
                db.ServerGroups.Add(serverGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serverGroup);
        }

        // GET: ServerGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerGroup serverGroup = db.ServerGroups.Find(id);
            if (serverGroup == null)
            {
                return HttpNotFound();
            }
            return View(serverGroup);
        }

        // POST: ServerGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServerGroupID,ServerGroupName,TSServerGroupID")] ServerGroup serverGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serverGroup).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serverGroup);
        }

        // GET: ServerGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerGroup serverGroup = db.ServerGroups.Find(id);
            if (serverGroup == null)
            {
                return HttpNotFound();
            }
            return View(serverGroup);
        }

        // POST: ServerGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServerGroup serverGroup = db.ServerGroups.Find(id);
            db.ServerGroups.Remove(serverGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/MooseShield/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MooseArmy TeamSpeak Authentication</title>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color: #151517 !important;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TS Authentication", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div>
        <div class="container body-content">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - MooseArmy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/MooseShield/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MooseArmy TeamSpeak Authentication</title>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/chameleonforms-twitterbootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/main.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/icomoon.css" />

    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="~/Content/assets/js/html5shiv.js"></script>
      <script src="~/Content/assets/js/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/jquery")


</head>

<body data-spy="scroll" data-offset="0" data-target="#navbar-main">
@*    <!-- Wrapper starts here -->
    <div id="wrapper">
        <!-- Navigation starts here -->
        <div id="menu_wrap">
            <!-- Menu starts here -->
            <div id="menu">
                <!-- Navbar -->
                <ul id="navbar">
                    @{
                    bool IsSysAdmin = (bool)ViewData["Role"];
                    if (IsSysAdmin)
                    {
                }
                }

                <li class="top_nav">
                    <a id="blog" href="#">System Admin</a>
                    <ul>
                        <li>@Html.ActionLink("Roles", "Index", "Roles")</li>
                        <li>@Html.ActionLink("Permissions", "Index", "Permissions")</li>
                    </ul>
                </li>
                <li class="top_nav">@Html.ActionLink("TS Privileges", "Create", "TeamSpeakUsers")
                    <ul>
                        <li>@Html.ActionLink("List Users", "Index", "TeamSpeakUsers")</li>
                        <li>@Html.ActionLink("Server Groups", "Index", "ServerGroups")</li>
                    </ul>
                </li>
            </ul>
         </div>
    </div>
        <!-- Navigation ends here -->
*@
     
        
            @{ 
                var user = EVE.SingleSignOn.SSOClient.GetCharacter;
            }
       
        <div id="navbar-main">
            <!-- Fixed navbar -->
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon icon-shield" style="font-size:30px; color:#3498db;"></span>
                        </button>
                        <a class="navbar-brand hidden-xs hidden-sm" href="#"><span class="icon icon-shield" style="font-size:18px; color:#3498db;"></span></a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="http://moosefed.com">Moose Federation</a></li>
                            @*<li> <a href="#" class="smoothScroll"> Admin</a></li>*@
                            @{

                                if (RBAC_ExtendedMethods.HasRole("Administrator", user))
                                {
                                    <li>@Html.ActionLink("Admin", "Index", "TeamSpeakUsers")</li>
                                }
                            }
                            <li> <a href="http://mps.moosehouseshow.com">MPS</a></li>
                            <li> <a href="https://fleets.moosefed.com">Fleet Tracker</a></li>
                            <li>@Html.ActionLink("Logout", "logout", "Login")</li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <!-- ==== HEADERWRAP ==== -->
        <div id="headerwrap" name="home">
            <header class="clearfix">
                @*<h3 class="section_title">@ViewBag.SectionTitle</h3><!-- This is your section title -->*@
                @RenderBody()
                @*<h1><span class="icon icon-shield"></span></h1>
                <p>A Bootstrap 3 One Page Theme.</p>
                <p>Exclusive for BlackTie.co.</p>*@
            </header>
        </div><!-- /headerwrap -->


        
        @*<div id="footer" class="panel-footer">
            
                <p class="text-center">&copy; @DateTime.Now.Year - MooseArmy</p>
            
        </div>*@
    

    
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    
    @RenderSection("scripts", required: false)
    <!-- Version: @(MooseShield.Core.Utils.VersionHelper.GetVersion()) -->
</body>
</html>