src/MooseShield/Models/TeamSpeakUser.cs
namespace MooseShield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class TeamSpeakUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamSpeakUser()
        {
            ServerGroups = new HashSet<ServerGroup>();
        }

        public int TeamSpeakUserID { get; set; }
        [Required,RegularExpression(@".{5,}\=$",ErrorMessage = "Do you even Unique ID BRO?! Be a doll and RTFM!")]
        public string UniqueID { get; set; }

        public string ServerGroup { get; set; }

        public string CharacterOwnerHash { get; set; }

        public string CharacterName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerGroup> ServerGroups { get; set; }
    }
}

src/MooseShield/Controllers/TeamSpeakUsersController.cs
using EVE.SingleSignOn;
using EVE.SingleSignOn.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MooseShield.Action_Filters;
using MooseShield.Models;

namespace MooseShield.Controllers
{
    //[RBAC]
    public class TeamSpeakUsersController : Controller
    {
        private TSAuthContext db = new TSAuthContext("Local");
        private ILog _log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: TeamSpeakUsers
        [RBACAttribute]
        public ActionResult Index()
        {
            return View(db.TeamSpeakUsers.OrderBy(x => x.CharacterName).ToList());
        }

        // GET: TeamSpeakUsers/Details/5
        [RBAC]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamSpeakUser teamSpeakUser = db.TeamSpeakUsers.Find(id);
            if (teamSpeakUser == null)
            {
                return HttpNotFound();
            }
            return View(teamSpeakUser);
        }


        // GET: TeamSpeakUsers/Create
        public ActionResult Create()
        {
            if (SSOClient.IsLoggedIn)
            {
                var loggedInCharacter = SSOClient.GetCharacter;
                RBACUser requestingUser = new RBACUser(loggedInCharacter.CharacterName);
                if (requestingUser.HasRole("Administrator"))
                {
                    ViewData["Role"] = true;
                    return View();
                }
                ViewData["Role"] = false;
                return View();
            }


            return RedirectToAction("Index", "Home");
        }

        // POST: TeamSpeakUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Create([Bind(Include = "TeamSpeakUserID,UniqueID")] TeamSpeakUser teamSpeakUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.TeamSpeakUsers.Where(u => u.UniqueID == teamSpeakUser.UniqueID).Single();
                    ViewBag.Message = "You have already been granted access to the Moose Federation TeamSpeak server.";
                }
                catch (Exception e)
                {
                    var loggedInCharacter = SSOClient.GetCharacter;
                    var currentUser = db.Users.Where(u => u.CharacterOwnerHash == loggedInCharacter.CharacterOwnerHash).Single();
                    teamSpeakUser.CharacterName = currentUser.CharacterName;

                    switch (currentUser.Corporation)
                    {
                        case "Moosearmy":
                            teamSpeakUser.ServerGroup = "7,17";
                            break;

                        case "Moosearmy Heavy Industries":
                            teamSpeakUser.ServerGroup = "7,17";
                            break;
                        case "Saints Of Havoc":
                            teamSpeakUser.ServerGroup = "7,21";
                            break;
                        default:
                            teamSpeakUser.ServerGroup = "7";
                            break;
                    }


                    // Retrieve the list of server group IDs
                    int[] ids = Array.ConvertAll(teamSpeakUser.ServerGroup.Split(','), int.Parse);
                    List<int> groupIds = ids.ToList();

                    // Assign groups to the user
                    if (await ServerGroupAssign.ServerGroupAssignment(teamSpeakUser.UniqueID, groupIds))
                    {
                        _log.Info($"Successfully added {groupIds.Count} groups to {teamSpeakUser.CharacterName} ({teamSpeakUser.UniqueID})");
                        teamSpeakUser.CharacterOwnerHash = loggedInCharacter.CharacterOwnerHash;
                        // Store in DB
                        db.TeamSpeakUsers.Add(teamSpeakUser);
                        db.SaveChanges();

                        return RedirectToAction("Success", "Home");
                    }

                    _log.Error($"Could not assign groups to {teamSpeakUser.CharacterName} ({teamSpeakUser.UniqueID})");
                    ModelState.AddModelError("", "It looks like you're not connected to the TS server. RTFM!");
                    return View();
                }

            }

            return View(teamSpeakUser);
        }

        // GET: TeamSpeakUsers/Edit/5
        [RBAC]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamSpeakUser teamSpeakUser = db.TeamSpeakUsers.Find(id);
            if (teamSpeakUser == null)
            {
                return HttpNotFound();
            }

            return View(teamSpeakUser);
        }

        // POST: TeamSpeakUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [RBAC]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Edit([Bind(Include = "TeamSpeakUserID,UniqueID,ServerGroup")] TeamSpeakUser teamSpeakUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Convert the updated server group list to an int[]
                    int[] newServerGroups = Array.ConvertAll(teamSpeakUser.ServerGroup.Split(','), int.Parse);
                    if (newServerGroups != null)
                    {
                        _log.Debug($"newServerGroups created: {newServerGroups}");
                    }

                    if (newServerGroups.Contains(6))
                    {
                        int removeSix = 6;
                        newServerGroups = newServerGroups.Where(v => v != removeSix).ToArray();
                    }
                    // Grab the current server group list, convert it to an int[]
                    TeamSpeakUser sg = null;
                    int[] _currentServerGroup = { };
                    _log.Debug("sg and _currentServerGroup created.");
                    using (var context = new TSAuthContext("Local"))
                    {
                        sg = context.TeamSpeakUsers.Where(s => s.UniqueID == teamSpeakUser.UniqueID).Single();
                        _currentServerGroup = Array.ConvertAll(sg.ServerGroup.Split(','), int.Parse);
                        _log.Debug($"_currentServerGroup: {_currentServerGroup.ToString()}");
                        if (newServerGroups.Count() < _currentServerGroup.Count())
                        {
                            List<int> _deleteServerGroups = _currentServerGroup.Except(newServerGroups).ToList();

                            await ServerGroupAssign.ServerGroupDelete(teamSpeakUser.UniqueID, _deleteServerGroups);
                            _log.Debug("Server Groups Deleted.");
                        }

                    }


                    // Get the difference between the arrays and assign it to _serverGroups
                    List<int> _serverGroups = newServerGroups.Except(_currentServerGroup).ToList();

                    SSOCharacter loggedInCharacter = SSOClient.GetCharacter;
                    User currentUser = db.Users.Where(u => u.CharacterOwnerHash == loggedInCharacter.CharacterOwnerHash).Single();
                    teamSpeakUser.CharacterName = currentUser.CharacterName;
                    teamSpeakUser.CharacterOwnerHash = loggedInCharacter.CharacterOwnerHash;
                    _log.Debug($"Char Name: {teamSpeakUser.CharacterName} : COH: {teamSpeakUser.CharacterOwnerHash}");
                    db.Entry(teamSpeakUser).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    _log.Debug("Database updated.");
                    await ServerGroupAssign.ServerGroupAssignment(teamSpeakUser.UniqueID, _serverGroups);
                    _log.Debug("TeamSpeak update.");
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    _log.Error("Encountered issues while trying to update user's server group.", e);
                }
            }
            return View(teamSpeakUser);
        }

        // GET: TeamSpeakUsers/Delete/5
        [RBAC]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamSpeakUser teamSpeakUser = db.TeamSpeakUsers.Find(id);
            if (teamSpeakUser == null)
            {
                return HttpNotFound();
            }
            return View(teamSpeakUser);
        }

        // POST: TeamSpeakUsers/Delete/5
        [RBAC]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TeamSpeakUser teamSpeakUser = db.TeamSpeakUsers.Find(id);
            db.TeamSpeakUsers.Remove(teamSpeakUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ServerGroupListPartial()

src/MooseShield/Views/TeamSpeakUsers/Create.cshtml
@model MooseShield.Models.TeamSpeakUser

@{
    ViewBag.Title = "Create";

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="main-form">
        <div class="form-horizontal center-block">
            <p>You must be connected to the server first</p>
            <h4 style="color:white;">New TeamSpeak User</h4>
            <span class="message"> @ViewBag.Message </span>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UniqueID, htmlAttributes: new { @class = "control-label col-md-2 white-label" }):
                <div class="col-md-8">
                    @Html.EditorFor(model => model.UniqueID, new { htmlAttributes = new { @class = "form-control", placeholder= "Enter your Unique ID (RTFM)" } })
                    @Html.ValidationMessageFor(model => model.UniqueID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2 col-md-offset-2">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            <h4>@Html.ActionLink("Click here for the Fucking Manual", "Instructions", "Home", null, new { @class = "btn btn-danger btn-lg" })</h4>
        </div>
    </div>
}


@*<div class="col-md-4">
            <img src="~/img/MooseFed-TS-Instructions.png" width="490" />
        </div>
    </div>*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/MooseShield/Views/TeamSpeakUsers/Delete.cshtml
@model MooseShield.Models.TeamSpeakUser

@{
    ViewBag.Title = "Delete TeamSpeak User";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete TeamSpeak User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UniqueID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniqueID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServerGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServerGroup)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/MooseShield/Views/TeamSpeakUsers/Details.cshtml
@model MooseShield.Models.TeamSpeakUser

@{
    ViewBag.Title = "TeamSpeak User Details";
}

<div>
    <h4>TeamSpeak User Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UniqueID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniqueID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServerGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServerGroup)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TeamSpeakUserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/MooseShield/Views/TeamSpeakUsers/Edit.cshtml
@model MooseShield.Models.TeamSpeakUser

@{
    ViewBag.Title = "Edit TeamSpeak User";
}




@*<h3 class="white-label">@{ViewBag.SectionTitle = "Edit User";} </h3>*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="edit-form">
        <div class="form-horizontal center-block">


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.TeamSpeakUserID)
            <h5 class="white-label">Add the Server Group IDs separated by a comma to give the user more privileges. To remove privileges, simply delete the ID.</h5>
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.CharacterName, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CharacterName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.CharacterName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UniqueID, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.UniqueID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.UniqueID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ServerGroup, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.ServerGroup, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ServerGroup, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-2">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

<br />
<div style="color: white;">    
    @Html.ActionLink("Back to List", "Index", "TeamSpeakUsers", htmlAttributes: new { @class = "white-label" })
</div>
<div id="ServerGroupsTable">

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            datatype: "text/plain",
            type: "GET",
            url: "/TeamSpeakUsers/ServerGroupListPartial",
            success: function (data) {
                $('#ServerGroupsTable').html(data);
            }
        });
    });
</script>

src/MooseShield/Views/TeamSpeakUsers/Index.cshtml
@model IEnumerable<MooseShield.Models.TeamSpeakUser>

@{
    ViewBag.Title = "TeamSpeak Users";
}

@*<h3>@{ViewBag.SectionTitle = "All Users";}</h3>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div>
<div class="table-responsive" style="margin: 1em;">
    <table class="table table-hover table-condensed">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CharacterName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniqueID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServerGroup)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CharacterOwnerHash)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>

                    @Html.ActionLink(item.CharacterName, "Edit", new { id = item.TeamSpeakUserID })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UniqueID)
                </td>
                <td width="10">
                    @Html.DisplayFor(modelItem => item.ServerGroup)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CharacterOwnerHash)
                </td>
                <td>

                    @*@Html.ActionLink("Details", "Details", new { id = item.TeamSpeakUserID }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.TeamSpeakUserID })
                </td>
            </tr>
        }

    </table>
</div>

src/MooseShield/Views/TeamSpeakUsers/_ServerGroupList.cshtml
@model IEnumerable<MooseShield.Models.ServerGroup>

@{
    if (Model == null)
    {
    <h2><font color="red">No Associated Groups...</font></h2>
    <br />
    }
    else
    {
        <div class="table-responsive">
            <table id="ServerGroupTable" class="table table-condensed table-bordered table-hover">
                <tbody>
                    <tr>
                        <th>
                            Server Group ID
                        </th>
                        <th>
                            Server Group
                        </th>
                    </tr>
                    @foreach (var group in Model)
                    {
                        <tr>
                            <td>
                                @group.TSServerGroupID
                            </td>
                            <td>
                                @group.ServerGroupName
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <br />
    }
}